name: megatel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^4.1.1
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  flutter_email_sender: ^6.0.1
  flutter_phoenix: ^1.0.0
  shared_preferences: ^2.0.8
  csc_picker: ^0.2.7
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  lottie: ^3.1.0
  timezone: ^0.9.3
  badges: ^3.1.2
  intl: ^0.18.0
  provider: ^6.0.4
  fluttertoast: ^8.0.7
  flutter_rating_bar: ^4.0.0
  audio_waveforms: ^1.0.5
  audioplayers: ^6.0.0
  flutter_sound: ^9.4.12
  passwordfield: ^0.2.0
  record: ^5.0.5
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.0.6
  mailer: ^6.1.0
  permission_handler: ^11.3.1
  chat_bubbles: ^1.5.0
  flutter_multi_formatter: ^2.0.2
  flutter_local_notifications: ^17.1.2
  animations: ^2.0.11
  path_provider: ^2.1.3
  translator: ^1.0.0
  just_audio: ^0.9.38
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "image/logo.png"

flutter:
  uses-material-design: true

  assets:
     - image/ppp.jpg
     - image/flags/es.svg
     - image/flags/gb.svg
     - image/flags/fr.svg
     - image/cards/mastercard.svg
     - image/cards/discover.svg
     - image/cards/amex.svg
     - image/cards/visa.svg
     - image/logo.png
     - image/languge/es.png
     - image/languge/fr.png
     - image/languge/us.png
     - image/2.png
     - image/logo1.png
     - gif/megalogo1.json
     - gif/loading.json
     - assets/audio/welcom.mp3
     - languages/en.json
     - languages/es.json
     - languages/fr.json
     - image/verif.jpeg
     - image/verf.png
     - image/set.png
     - image/apply.png
     - image/fb.png
     - image/bac.jpeg
     - image/bac1.jpeg
     - image/go.png
     - image/ap.png
